/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passportautomationsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AdminViewStatus extends javax.swing.JFrame {
    private String applicationID;
    private Admin admin;

    /**
     * Creates new form AdminViewStatus
     */
    public AdminViewStatus(String applicationID, Admin admin) {
        initComponents();
        this.applicationID = applicationID;
        this.admin = admin;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        homepagename = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        policeUpdateBtn = new javax.swing.JButton();
        applicationUpdateBtn = new javax.swing.JButton();
        passportUpdateBtn = new javax.swing.JButton();
        paymentUpdateBtn = new javax.swing.JButton();
        backBTn = new javax.swing.JButton();
        policeStatus = new javax.swing.JComboBox<>();
        applicationStatus = new javax.swing.JComboBox<>();
        paymentStatus = new javax.swing.JComboBox<>();
        passportStatus = new javax.swing.JComboBox<>();
        exitBtn = new javax.swing.JButton();
        adminMainPageBackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN VIEW STATUS");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        homepagename.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        homepagename.setForeground(new java.awt.Color(0, 51, 51));
        homepagename.setText("VIEW STATUS");

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setText("Police Status :");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setText("Payment Status :");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel3.setText("Application Status :");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel4.setText("Passport Status :");

        policeUpdateBtn.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        policeUpdateBtn.setText("UPDATE");
        policeUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policeUpdateBtnActionPerformed(evt);
            }
        });

        applicationUpdateBtn.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        applicationUpdateBtn.setText("UPDATE");
        applicationUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicationUpdateBtnActionPerformed(evt);
            }
        });

        passportUpdateBtn.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        passportUpdateBtn.setText("UPDATE");
        passportUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passportUpdateBtnActionPerformed(evt);
            }
        });

        paymentUpdateBtn.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        paymentUpdateBtn.setText("UPDATE");
        paymentUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentUpdateBtnActionPerformed(evt);
            }
        });

        backBTn.setFont(new java.awt.Font("Rockwell", 1, 19)); // NOI18N
        backBTn.setText("BACK");
        backBTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTnActionPerformed(evt);
            }
        });

        policeStatus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        policeStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Police Status", "VERIFIED", "PENDING", "REJECTED" }));

        applicationStatus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        applicationStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Application Status", "VERIFIED", "PENDING", "REJECTED" }));

        paymentStatus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        paymentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Payment Status", "VERIFIED", "PENDING", "REJECTED" }));

        passportStatus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        passportStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Passport Status", "VERIFIED", "PENDING", "REJECTED" }));

        exitBtn.setFont(new java.awt.Font("Rockwell", 1, 19)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        adminMainPageBackBtn.setFont(new java.awt.Font("Rockwell", 1, 19)); // NOI18N
        adminMainPageBackBtn.setText("MAIN PAGE");
        adminMainPageBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminMainPageBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(homepagename)
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(backBTn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adminMainPageBackBtn)
                        .addGap(53, 53, 53)
                        .addComponent(exitBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(policeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(applicationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passportStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(policeUpdateBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(paymentUpdateBtn)
                            .addComponent(applicationUpdateBtn)
                            .addComponent(passportUpdateBtn))))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(homepagename)
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(policeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(applicationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(passportStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(policeUpdateBtn)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paymentUpdateBtn)
                            .addComponent(paymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(applicationUpdateBtn)
                        .addGap(55, 55, 55)
                        .addComponent(passportUpdateBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBTn)
                    .addComponent(exitBtn)
                    .addComponent(adminMainPageBackBtn))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void policeUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policeUpdateBtnActionPerformed
        // TODO add your handling code here:
        String applicationID = this.applicationID; // Replace with your method to get the application ID

        // Call the update method
        if (admin != null) {
            
        String selectedPoliceStatus = (String) policeStatus.getSelectedItem();
        boolean policePending = selectedPoliceStatus.equals("PENDING");
        boolean policeVerified = selectedPoliceStatus.equals("VERIFIED");
        boolean policeRejected = selectedPoliceStatus.equals("REJECTED");
        admin.updatePoliceStatus(applicationID, policePending, policeVerified, policeRejected);
        
        String successMessage = "Updated successfully.";
        JOptionPane.showMessageDialog(this, successMessage, "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Update failed.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_policeUpdateBtnActionPerformed

    private void applicationUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicationUpdateBtnActionPerformed
        // TODO add your handling code here:
        
        if (admin != null) {
        String selectedApplicationStatus = (String) applicationStatus.getSelectedItem();
        boolean applicationPending = selectedApplicationStatus.equals("PENDING");
        boolean applicationVerified = selectedApplicationStatus.equals("VERIFIED");
        boolean applicationRejected = selectedApplicationStatus.equals("REJECTED");
        admin.updateApplicationStatus(applicationID, applicationPending, applicationVerified, applicationRejected);
        
        
        String successMessage = "Updated successfully.";
        JOptionPane.showMessageDialog(this, successMessage, "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Update failed.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_applicationUpdateBtnActionPerformed

    private void passportUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passportUpdateBtnActionPerformed
        // TODO add your handling code here:
        
        if (admin != null) {
        String selectedPassportStatus = (String) passportStatus.getSelectedItem();
        boolean passportPending = selectedPassportStatus.equals("PENDING");
        boolean passportVerified = selectedPassportStatus.equals("VERIFIED");
        boolean passportRejected = selectedPassportStatus.equals("REJECTED");
        admin.updatePassportStatus(applicationID, passportPending, passportVerified, passportRejected);
        
        
        String successMessage = "Updated successfully.";
        JOptionPane.showMessageDialog(this, successMessage, "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Update failed.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_passportUpdateBtnActionPerformed

    private void paymentUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentUpdateBtnActionPerformed
        // TODO add your handling code here:
        
        if (admin != null) {
        String selectedPaymentStatus = (String) paymentStatus.getSelectedItem();
        boolean paymentPending = selectedPaymentStatus.equals("PENDING");
        boolean paymentVerified = selectedPaymentStatus.equals("VERIFIED");
        boolean paymentRejected = selectedPaymentStatus.equals("REJECTED");
        admin.updatePaymentStatus(applicationID, paymentPending, paymentVerified, paymentRejected);
        
        
        String successMessage = "Updated successfully.";
        JOptionPane.showMessageDialog(this, successMessage, "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Update failed.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_paymentUpdateBtnActionPerformed

    private void backBTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTnActionPerformed
        // TODO add your handling code here:        
        AdminView adminview = new AdminView();
        adminview.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        int response =  JOptionPane.showConfirmDialog(null,
            "Are you sure to exit?", "Exit Confirmation",
            JOptionPane.YES_NO_OPTION);

        //if click on yes,clear fields
        if(response ==JOptionPane.YES_OPTION ) {
            this.dispose();
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void adminMainPageBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminMainPageBackBtnActionPerformed
        // TODO add your handling code here:
        AdminSelection adminselection = new AdminSelection();
        adminselection.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminMainPageBackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminMainPageBackBtn;
    private javax.swing.JComboBox<String> applicationStatus;
    private javax.swing.JButton applicationUpdateBtn;
    private javax.swing.JButton backBTn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel homepagename;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> passportStatus;
    private javax.swing.JButton passportUpdateBtn;
    private javax.swing.JComboBox<String> paymentStatus;
    private javax.swing.JButton paymentUpdateBtn;
    private javax.swing.JComboBox<String> policeStatus;
    private javax.swing.JButton policeUpdateBtn;
    // End of variables declaration//GEN-END:variables

}
