/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passportautomationsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ApplicantRegister extends javax.swing.JFrame {

    private int generatedRegID;

    /**
     * Creates new form Register
     */
    public ApplicantRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        applicantregistration = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        password2 = new javax.swing.JLabel();
        reenterpassword3 = new javax.swing.JLabel();
        registrationUsernameInput = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        registrationPasswordInput = new javax.swing.JPasswordField();
        registrationReEnterPasswordInput = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APPLICANT REGISTRATION");
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        applicantregistration.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        applicantregistration.setForeground(new java.awt.Color(0, 51, 51));
        applicantregistration.setText("APPLICANT REGISTRATION");

        username1.setBackground(new java.awt.Color(51, 51, 51));
        username1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        username1.setText("User Name :");

        password2.setBackground(new java.awt.Color(51, 51, 51));
        password2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password2.setText("Password :");

        reenterpassword3.setBackground(new java.awt.Color(51, 51, 51));
        reenterpassword3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reenterpassword3.setText("Re - Enter Password :");

        registrationUsernameInput.setBackground(new java.awt.Color(204, 255, 255));

        registerBtn.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        registerBtn.setText("REGISTER");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        registrationPasswordInput.setBackground(new java.awt.Color(204, 255, 255));

        registrationReEnterPasswordInput.setBackground(new java.awt.Color(204, 255, 255));
        registrationReEnterPasswordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationReEnterPasswordInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(170, 170, 170)
                        .addComponent(registerBtn))
                    .addComponent(applicantregistration)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(username1)
                            .addComponent(password2)
                            .addComponent(reenterpassword3))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(registrationUsernameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(registrationPasswordInput)
                            .addComponent(registrationReEnterPasswordInput))))
                .addGap(0, 74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(applicantregistration)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrationUsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password2)
                    .addComponent(registrationPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reenterpassword3)
                    .addComponent(registrationReEnterPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn)
                    .addComponent(backBtn))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        String username = registrationUsernameInput.getText();
        String password = registrationPasswordInput.getText();
        String registrationReEnter = registrationReEnterPasswordInput.getText();
        
				 
	if (username.isEmpty() || password.isEmpty() || registrationReEnter.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }

        if (!password.equals(registrationReEnter)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        if (password.length() > 8) {
        JOptionPane.showMessageDialog(this, "Password should be 8 characters or less.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }

        Applicant applicant = new Applicant(username, password);
        int applicantID = applicant.registerApplicant(username, password);

        
        if (applicantID != -1) {
        // Display a success message with the generated registration ID
        String successMessage = "Registration successful. Your Registration ID is: " + applicantID;
        JOptionPane.showMessageDialog(this, successMessage, "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Registration failed.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        // Redirect to the login page
        ApplicantLogin login = new ApplicantLogin();
        login.setVisible(true);
        this.dispose(); // Close the current registration form
    
    
    }//GEN-LAST:event_registerBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        ApplicantLogin login = new ApplicantLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void registrationReEnterPasswordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationReEnterPasswordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrationReEnterPasswordInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicantRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicantRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicantRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicantRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicantRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel applicantregistration;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel password2;
    private javax.swing.JLabel reenterpassword3;
    private javax.swing.JButton registerBtn;
    private javax.swing.JPasswordField registrationPasswordInput;
    private javax.swing.JPasswordField registrationReEnterPasswordInput;
    private javax.swing.JTextField registrationUsernameInput;
    private javax.swing.JLabel username1;
    // End of variables declaration//GEN-END:variables
}
