/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passportautomationsystem;

/**
 *
 * @author User
 */
public class ApplicantSelection extends javax.swing.JFrame {

    /**
     * Creates new form applicantSelection
     */
    public ApplicantSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        applicantregistration = new javax.swing.JLabel();
        checkstatusBtn = new javax.swing.JButton();
        applyforpassportBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        appointmentScheduleBtn = new javax.swing.JButton();
        viewReportBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APPLICANT SELECTION");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        applicantregistration.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        applicantregistration.setForeground(new java.awt.Color(0, 51, 51));
        applicantregistration.setText("APPLICANT");

        checkstatusBtn.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        checkstatusBtn.setText("Check Status");
        checkstatusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkstatusBtnActionPerformed(evt);
            }
        });

        applyforpassportBtn.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        applyforpassportBtn.setText("Apply for Passport");
        applyforpassportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyforpassportBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        appointmentScheduleBtn.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        appointmentScheduleBtn.setText("Appointment Schedule");
        appointmentScheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentScheduleBtnActionPerformed(evt);
            }
        });

        viewReportBtn.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        viewReportBtn.setText("View Report");
        viewReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(applicantregistration))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(backBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(applyforpassportBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(checkstatusBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(viewReportBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(appointmentScheduleBtn)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(applicantregistration)
                .addGap(49, 49, 49)
                .addComponent(applyforpassportBtn)
                .addGap(45, 45, 45)
                .addComponent(checkstatusBtn)
                .addGap(37, 37, 37)
                .addComponent(appointmentScheduleBtn)
                .addGap(32, 32, 32)
                .addComponent(viewReportBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkstatusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkstatusBtnActionPerformed
        // TODO add your handling code here:

        ApplicantCheckStatus checkstatus = new ApplicantCheckStatus();
        checkstatus.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_checkstatusBtnActionPerformed

    private void applyforpassportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyforpassportBtnActionPerformed
        // TODO add your handling code here:
        ApplicantNICValidation nicvalidation = new ApplicantNICValidation();
        nicvalidation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_applyforpassportBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        ApplicantLogin login = new ApplicantLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void appointmentScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentScheduleBtnActionPerformed
        // TODO add your handling code here:
        ApplicantAppointment applicantappointment = new ApplicantAppointment();
        applicantappointment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_appointmentScheduleBtnActionPerformed

    private void viewReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReportBtnActionPerformed
        // TODO add your handling code here:
        ApplicantReportView applicantreportview = new ApplicantReportView();
        applicantreportview.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewReportBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicantSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicantSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicantSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicantSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicantSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel applicantregistration;
    private javax.swing.JButton applyforpassportBtn;
    private javax.swing.JButton appointmentScheduleBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton checkstatusBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton viewReportBtn;
    // End of variables declaration//GEN-END:variables
}
